import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState } from "../store";
import { api } from "../../api";
import { NewOrderFormData } from "../../components/forms/newOrderForm/NewOrderForm";

export interface Order {
  _id?: string;
  shishaId: string | undefined;
  userFullName: string;
  userAddress: string;
  dateOfDelivery: string;
  timeOfDelivery: string;
  userTelNumber: string;
  extras?: string[];
  total: number;
  userNote?: string;
  createdAt?: string;
  done?: boolean;
  ownerNote?: string;
}

export interface OrdersState {
  orders: Order[];
  status: "idle" | "loading" | "successful" | "failed";
  messages: { [key: string]: string };
  newOrderDate: string | null;
  offeredExtras: Extra[];
  selectedExtras: Extra[];
}

export interface Extra {
  name: string;
  price: number;
}

const initialState: OrdersState = {
  status: "idle",
  orders: [],
  messages: {},
  newOrderDate: null,
  offeredExtras: [],
  selectedExtras: [],
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchOrders = createAsyncThunk("orders/fetchOrders", async () => {
  try {
    const response = await api.get("/orders");
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  } catch (error: any) {
    throw new Error(JSON.stringify(error.response.data));
  }
});

export const postNewOrder = createAsyncThunk(
  "orders/postNewOrder",
  async (newOrder: NewOrderFormData) => {
    try {
      const response = await api.post("/order/new", newOrder);
      console.log(response.status);
      if (response.status === 201) {
        const response = await api.get("/orders");
        // The value we return becomes the `fulfilled` action payload
        return response.data;
      }
    } catch (error: any) {
      throw new Error(JSON.stringify(error.response.data));
    }
  }
);

export const ordersSlice = createSlice({
  name: "orders",
  initialState,
  // // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    updateSelectedExtras: (state, action: PayloadAction<Extra[]>) => {
      state.selectedExtras = action.payload || [];
    },
    updateNewOrderDate: (state, action: PayloadAction<string>) => {
      state.newOrderDate = action.payload;
    },
    // decrement: (state) => {
    //   state.value -= 1;
    // },
    // // Use the PayloadAction type to declare the contents of `action.payload`
    // incrementByAmount: (state, action: PayloadAction<number>) => {
    //   state.value += action.payload;
    // },
  },
  // // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchOrders.pending, (state) => {
        state.status = "loading";
      })
      .addCase(fetchOrders.fulfilled, (state, action) => {
        state.status = "successful";
        state.orders = action.payload;
      })
      .addCase(fetchOrders.rejected, (state, action: any) => {
        state.status = "failed";
        state.messages = JSON.parse(action.error.message);
      });
    builder
      .addCase(postNewOrder.pending, (state) => {
        state.status = "loading";
      })
      .addCase(postNewOrder.fulfilled, (state, action) => {
        state.status = "successful";
        state.orders = action.payload;
      })
      .addCase(postNewOrder.rejected, (state, action: any) => {
        state.status = "failed";
        state.messages = JSON.parse(action.error.message);
      });
  },
});

export const { updateSelectedExtras, updateNewOrderDate } = ordersSlice.actions;

// // The function below is called a selector and allows us to select a value from
// // the state. Selectors can also be defined inline where they're used instead of
// // in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`

// // Posible selector bellow just for reference not used
export const selectOrders = (state: RootState) => state.orders.orders;

// // We can also write thunks by hand, which may contain both sync and async logic.
// // Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
//   (amount: number): AppThunk =>
//   (dispatch, getState) => {
//     const currentValue = selectCount(getState());
//     if (currentValue % 2 === 1) {
//       dispatch(incrementByAmount(amount));
//     }
//   };

export default ordersSlice.reducer;
